import Head from 'next/head'
import Image from 'next/image'
import LogoImage from 'assets/image/oio.png'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'

export default function Home() {
    const [start, setStart] = useState<Boolean>(false)
    const router = useRouter()
    useEffect(()=>{
        setTimeout(()=> {
            setStart(true)
        },3000)
        setTimeout(()=> {
            router.push('/start')
        },3600)
    },[]);
    useEffect(()=>{
        start && setStart(true)
    },[start])
    return (
        <>
            <Head>
                <title>Next-OIO</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='w-screen min-h-screen flex justify-center items-center'>
                <div className='-mt-[5vh]'>
                    <Image
                        src={LogoImage}
                        width={300}
                        height={300}
                        alt='OIO'
                        className={`animate-bounce transition ${start === true && 'opacity-0'}`}
                    />
                </div>
                <p className='absolute bottom-[10vh] text-[22px] text-gray-500'>Made by MinSeok</p>
            </main>
        </>
    )
}
